//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Infrastructure.Toolkits.Resources;

using System;


/// <summary>
///   用於查詢當地語系化字串等的強類型資源類別。
/// </summary>
// 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
// 類別透過 RDemoen 或 Visual Studio 這類工具。
// 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 RDemoen
// (利用 /str 選項)，或重建您的 VS 專案。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class MessageResource
{

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal MessageResource()
    {
    }

    /// <summary>
    ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Infrastructure.Toolkits.Resources.MessageResource", typeof(MessageResource).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
    ///   使用這個強類型資源類別的資源查閱。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   查詢類似 參數傳入異常 {message} 的當地語系化字串。
    /// </summary>
    public static string ArgumentExceptionMessage
    {
        get
        {
            return ResourceManager.GetString("ArgumentExceptionMessage", resourceCulture);
        }
    }

    /// <summary>
    ///   查詢類似 Bizform Endpoint 認證失敗 {message} 的當地語系化字串。
    /// </summary>
    public static string BizformAuthorizationExceptionMessge
    {
        get
        {
            return ResourceManager.GetString("BizformAuthorizationExceptionMessge", resourceCulture);
        }
    }

    /// <summary>
    ///   查詢類似 系統參數設定異常 {message} 的當地語系化字串。
    /// </summary>
    public static string ConfigNullExceptionMessage
    {
        get
        {
            return ResourceManager.GetString("ConfigNullExceptionMessage", resourceCulture);
        }
    }

    /// <summary>
    ///   查詢類似 檔案服務處理異常 {message} 的當地語系化字串。
    /// </summary>
    public static string FileServiceExceptionMessage
    {
        get
        {
            return ResourceManager.GetString("FileServiceExceptionMessage", resourceCulture);
        }
    }

    /// <summary>
    ///   查詢類似 發信服務處理異常 {message} 的當地語系化字串。
    /// </summary>
    public static string MailSendExceptionMessage
    {
        get
        {
            return ResourceManager.GetString("MailSendExceptionMessage", resourceCulture);
        }
    }
}
